### PR TITLE
Implement design proposal for website search

### PR DESCRIPTION
**Pull request by snaegle**
Related to: AAC-713

### CODE REVIEW

**Comment by nilswindisch** [comment]
I don't have a working website search and all my question got ghosted (in dailys and review), so I'm not able to review this PR.

**Comment by nilswindisch** [comment]
Whatever search term I use the only page that gets found is "Medieval Craft Recipe Books" which makes reviewing a PR for a list of results almost impossible.

**Comment by snaegle** [comment]
How about using "*" as searchterm?

**Comment by nilswindisch** [comment]
I don't see the point in showing the relevance.

**Comment by nilswindisch** [comment]
"Read More" ist missing the visually hidden text to clarify where the link leads to.

**Comment by nilswindisch** [comment]
"Read More" is an A, so using BUTTON is a. not necessary and b. misleading as BUTTON is reserved for state changing action.

**Comment by nilswindisch** [comment]
I don't see the point in showing how long the search took to find some results. How is this helping the user in his/her endeavour?

**Comment by nilswindisch** [comment]
The drop down to select the amount of hits per page is visually not identifiable and drop down.

**Comment by nilswindisch** [comment]
Here you can see my proposal how the pagination could look like: https://projects.invisionapp.com/d/main#/console/10197043/237594236/preview

**Comment by nilswindisch** [comment]
I propose to use inverted buttons (links!) for "Read More". exemplary: https://projects.invisionapp.com/d/main#/console/10197043/237594236/preview

**Review by nilswindisch — CHANGES_REQUESTED** [review]
➡ comments

**Comment by nilswindisch** [comment]
screenshot 2017-10-09 11 24 26
Dropdown says 10 per page, but only 4 out of 7 are visible

**Comment by nilswindisch** [comment]
not sure about the possible merge conflicts, maybe you can resolve them first?

**Pull request merged**
