### PR TITLE
Add page title prefix

### PR DESCRIPTION
**Pull request by ipf**
This patch requires the extension metaseo (webdevops/metaseo) to be
available in the system. It adds the prefix to all page titles and also
provides more sophisticated SEO features, that may be required.

Resolves: AAC-664

### CODE REVIEW

**Review by snaegle — APPROVED** [review]
* add extension 
* add includes of extension
* empty caches

**Comment by ipf** [comment]
The TypoScript is added automatically now

**Comment by snaegle** [comment]
Now, nothing has to be included anymore.

**Comment by snaegle** [comment]
Sorry, just wanted to add comment, not closing!

**Pull request merged**
