### PR TITLE
Show RSS-Feed icon in the last line of page

### PR DESCRIPTION
**Pull request by Blache**
and browser auto-detection of the feed on news pages

Resolves AAC-564 and AAC-565

### CODE REVIEW

**Comment by nilswindisch** [comment]
screenshot 2017-10-16 09 21 44

Do you get the same error?

The feed is referenced in html head meta, but I don't see an icon in the last section.

**Comment by snaegle** [comment]
@nilswindisch  To see the icon, you might have to delete typo3temp/*

**Comment by nilswindisch** [comment]
my local setting might be wrong? The is the source code as interpreted by my browser
screenshot 2017-10-16 09 32 31

**Comment by snaegle** [comment]
@nilswindisch RSS must be configured as described in JIRA in your root template.
ids.rss = ?type=6890

**Review by snaegle — APPROVED** [review]

**Pull request merged**
